name: Run Python Tests

# Trigger workflow on pushes and pull requests to these branches
on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  test:
    runs-on: ubuntu-latest   # Use latest Ubuntu VM provided by GitHub

    steps:
      # Step 1: Checkout repository code so the workflow can access it
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'   # Match your local Python version

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Run pytest tests
      - name: Run tests
        run: |
          pytest -v --disable-warnings
